spring.application.name=VehicleServicesManagement
spring.datasource.url=jdbc:mysql://localhost:3306/roy
spring.datasource.username=root
spring.datasource.password=21hm1a05C0+
# Hibernate dialect for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in the logs
spring.jpa.show-sql=true

